title: Interpreting Video Features of Deep Net Classifiers
description: Supplementary material for the paper Interpreting Video Features: a Comparison of 3D Convolutional Networks and Convolutional LSTM Networks
show_downloads: false
theme: jekyll-theme-cayman
